services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - networkcasopractico

  sqlserver:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    container_name: sqlserver-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Express"
      TZ: ${TZ}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - networkcasopractico

  client-service:
    build:
      context: .
      dockerfile: client-service/Dockerfile
    container_name: client-service
    restart: always
    ports:
      - "5000:8080"  # Puerto externo:interno (ajustable)
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TZ: ${TZ}
      LOG_DIR: /app/logs  
      ConnectionStrings__MysqlConnection: "Server=mysql-db;Port=3306;Database=${MYSQL_DATABASE};Uid=root;Pwd=${MYSQL_ROOT_PASSWORD};"
      RabbitMQSettings__Host: ${RABBITMQ_HOST}
      RabbitMQSettings__Puerto: ${RABBITMQ_PORT}
      RabbitMQSettings__Usuario: ${RABBITMQ_DEFAULT_USER}
      RabbitMQSettings__Contrasena: ${RABBITMQ_DEFAULT_PASS}
      RabbitMQSettings__TareaAsignadaQueue: ${RABBITMQ_TASK_QUEUE}
      EmailSettings__Host: ${EMAIL_HOST}
      EmailSettings__Puerto: ${EMAIL_PORT}
      EmailSettings__Usuario: ${EMAIL_USER}
      EmailSettings__Contrasena: ${EMAIL_PASS}
      EmailSettings__Emisor: ${EMAIL_USER}
    depends_on:
      - mysql
      - rabbitmq
    volumes:
      - client_logs:/app/logs
    networks:
      - networkcasopractico

  task-service:
    build:
      context: .
      dockerfile: task-service/Dockerfile
    container_name: task-service
    restart: always
    ports:
      - "5001:8080"  # Puerto externo:interno (ajustable)
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TZ: ${TZ}
      LOG_DIR: /app/logs  
      ConnectionStrings__SqlServerConnection: "Server=sqlserver-db,1433;Database=${MSSQL_DB};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true;"
      FtpSettings__Host: ${FTP_HOST}
      FtpSettings__Usuario: ${FTP_USER}
      FtpSettings__Contrasena: ${FTP_PASS}
      FtpSettings__RutaPendientes: ${FTP_FOLDER_PENDING}
      FtpSettings__RutaProcesados: ${FTP_FOLDER_PROCESSED}
      FtpSettings__RutaErrores: ${FTP_FOLDER_ERROR}
      FtpSettings__IntervaloMinutos: ${FTP_INTERVAL_MINUTE}
      RabbitMQSettings__Host: ${RABBITMQ_HOST}
      RabbitMQSettings__Puerto: ${RABBITMQ_PORT}
      RabbitMQSettings__Usuario: ${RABBITMQ_DEFAULT_USER}
      RabbitMQSettings__Contrasena: ${RABBITMQ_DEFAULT_PASS}
      RabbitMQSettings__TareaAsignadaQueue: ${RABBITMQ_TASK_QUEUE}
      ClientSettings__ClientByIdUrl: ${CLIENT_SERVICE_BY_ID_URL}
    depends_on:
      - sqlserver
      - rabbitmq
      - ftp-server
    volumes:
      - task_logs:/app/logs
    networks:
      - networkcasopractico
  
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     # para los microservicios
      - "15672:15672"   # interfaz web
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - networkcasopractico
  
  apigateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client-service
      - task-service
    networks:
      - networkcasopractico

  ftp-server:
    image: fauria/vsftpd
    container_name: ftp-server
    restart: always
    ports:
      - "21:21"
      - "21100-21110:21100-21110"  # Rango de puertos pasivos
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
      PASV_ADDRESS: 192.168.1.30  # O tu IP si accedes desde fuera
    volumes:
      - ./ftp/data:/home/vsftpd
    networks:
      - networkcasopractico

volumes:
  mysql_data:
  sqlserver_data:
  client_logs:
  task_logs:
  ftp_data:
  rabbitmq_data:

networks:
  networkcasopractico: